### PR TITLE
Daily historical data from Naver Finance

### PR DESCRIPTION
**Pull request by suminb**
This PR adds abilities to fetch daily historical data from [Naver Finance](https://finance.naver.com), which serves Korean (KOSPI, KOSDAQ) market data.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] passes `black --check pandas_datareader`
- [ ] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by addisonlynch** [comment]
Thanks. At first glance needs to documentation (entry to WHATSNEW and ``remote-data.rst``. Will take further look soon.

**Comment by suminb** [comment]
Sounds good. I will look into documentation stuff.

**Comment by suminb** [comment]
I've noticed the vast majority of data readers use `date` as an index (of a `DataFrame`). Should I also follow the trend?

**Comment by addisonlynch** [comment]
@suminb the resulting df should be indexed by a ``DatetimeIndex``

**Comment by suminb** [comment]
Alright. Put some documentation and make the `Date` column as an index. But I don't see`docs/source/whatsnew/vLATEST.txt` file. Should I make one?

**Comment by suminb** [comment]
Any thoughts on this?

**Comment by bashtage** [comment]
Thanks!

**Pull request merged**
