### PR TITLE
ENH: Support Eurostat

### PR DESCRIPTION
**Pull request by sinhrks**
```
import pandas_datareader.data as web

web.DataReader("tran_sf_railac", 'eurostat')
# ACCIDENT    Collisions of trains, including collisions with obstacles within the clearance gauge  \
# UNIT                                                                                      Number   
# GEO                                                                                      Austria   
# FREQ                                                                                      Annual   
# TIME_PERIOD                                                                                        
# 2010-01-01                                                   3                                     
# 2011-01-01                                                   2                                     
# 2012-01-01                                                   1                                     
# 2013-01-01                                                   4                                     
# 
# ...
# 
# [4 rows x 210 columns]
```

### CODE REVIEW

**Comment by davidastephens** [comment]
Thanks - you are on a roll!

**Comment by davidastephens** [comment]
Can you rebase and I will merge?  Thanks!

**Comment by sinhrks** [comment]
Sure. Rebased.

**Comment by davidastephens** [comment]
Thanks.

**Pull request merged**
