### PR TITLE
DOC: start documentation for pandas-datareader

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
I just did a sphinx-quickstart, added the current remote_data.rst file from pandas, and adapted this a little bit.

Further to do:
- [ ] Add reference docs (docstrings)
- [ ] set up read the docs

### CODE REVIEW

**Comment by femtotrader** [comment]
it will be nice if doc for pandas-datareader could be available on readthedocs https://readthedocs.org/

**Comment by jorisvandenbossche** [comment]
@femtotrader yes, certainly! I put that as a to do item above

**Comment by femtotrader** [comment]
One file per datareader is probably a way to go (for doc but probably for code too).

It will become much easier to add new datareader this way.

**Comment by jorisvandenbossche** [comment]
I am going the merge this, to be able to test it with read the docs

**Comment by jorisvandenbossche** [comment]
The current docs are up here: http://pandas-datareader.readthedocs.org/en/latest/index.html

**Comment by jorisvandenbossche** [comment]
@dstephens99 For the docs, do you have a readthedocs.org account? (you can login with a github account) Then I can maybe add you as maintainer, so I am not the only one with access to the doc build.

**Comment by femtotrader** [comment]
Could you add a badge for doc to README.rst ?
see http://docs.readthedocs.org/en/latest/badges.html
and https://readthedocs.org/projects/pandas-datareader/

reStructuredText

```
.. image:: https://readthedocs.org/projects/pandas-datareader/badge/?version=latest
:target: https://readthedocs.org/projects/pandas-datareader/?badge=latest
:alt: Documentation Status
```
                
Markdown

```
[![Documentation Status](https://readthedocs.org/projects/pandas-datareader/badge/?version=latest)](https://readthedocs.org/projects/pandas-datareader/?badge=latest)
```                

HTML
``` 
<a href='https://readthedocs.org/projects/pandas-datareader/?badge=latest'>
    <img src='https://readthedocs.org/projects/pandas-datareader/badge/?version=latest' alt='Documentation Status' />
</a>
```

It will be easier to find doc from GitHub repository.

**Comment by jorisvandenbossche** [comment]
@femtotrader voila: #42

**Comment by jorisvandenbossche** [comment]
@femtotrader Thanks for the idea!

**Comment by femtotrader** [comment]
Merci Monsieur.

**Pull request merged**
