### PR TITLE
skip tests that fail on travis.

### PR DESCRIPTION
**Pull request by graingert**
You should strongly consider using a tool like [vcrpy](https://github.com/kevin1024/vcrpy), to remove the dependency on third party APIs in your tests.

### CODE REVIEW

**Comment by jreback** [comment]
much better to actually fix the tests :> skipping things can easily hide errors.

**Comment by gfyoung** [comment]
Some I think are fixable.  But there's one that's failing because the CSV data returned can't be parsed properly by `pandas`...not sure if that's one we can control.

**Comment by graingert** [comment]
Sure, but better to have travis pass so PRs can be merged

**Comment by gfyoung** [comment]
> You should strongly consider using a tool like vcrpy, to remove the dependency on third party APIs in your tests.

But these tests aren't meant to be that controlled.  They're testing to make sure that the data from these sources is being returned as expected.  Thus, we do want to make sure our code remains compatible with their API at all times.

**Comment by gfyoung** [comment]
> Sure, but better to have Travis pass, so PRs can be merged

That's a double-edged sword there (skipping at will might actually be hiding errors in your implementation).  I agree with @jreback that it is better to figure out why tests are failing and patch if necessary (I imagine you and the maintainers can tell whether your changes are causing new failures).  As I said before, some of them are fixable, so I would patching as many as you can and skipping any that are out of our control.

**Comment by jreback** [comment]
@graingert 

i think fixing these are in everyone's interesting. sure some of these should be more smoke tests, but I think testing for valid data for specific fixes dates is really good. if the tests ever DO fail, then you know something has changed.

**Comment by graingert** [comment]
If you want to test that the api hasn't changed you should have a set of
separate tests that are run with Travis cron. All regular CI tests should
pass without network access

**Comment by gfyoung** [comment]
> All regular CI tests should pass without network access

Except that if the repository has a lot of functionality that depends on interfacing with other data sources, like this one.

Ultimately, you can debate what the test should be like or organized, but something tells me this PR isn't getting merged as is unless some of those tests are patched or you can provide convincing reasons as to why those tests are not fixable.

**Comment by graingert** [comment]
You can have tests that check 3rd party endpoints, but they should just
check the real response matches the fixtures

**Comment by gfyoung** [comment]
> You can have tests that check 3rd party endpoints, but they should just
check the real response matches the fixtures

What you seem to be pushing for is that there should be a separation between testing functionality and interfacing with 3rd party data sources.  Sure, but that doesn't the change fact that there needs to be tests that integrate everything together, which is what we have currently.

**Pull request closed without merging**
