### PR TITLE
WIP: Issue #394: Fixed google url

### PR DESCRIPTION
**Pull request by soon**
Issue #394

WIP until tests on the master branch will be fixed: https://github.com/pydata/pandas-datareader/pull/403

### CODE REVIEW

**Comment by TyrelCB** [comment]
edited the url on my side, still failing

**Comment by rsvp** [comment]
Why is the build failing? Maybe try "https" instead of "http".

**Comment by soon** [comment]
@rsvp No. As you can see, I have pushed a dummy commit to check if the master branch passes all tests. It does not. So that, we firstly have to fix failing tests

**Comment by soon** [comment]
Moved that commit to a separate PR: https://github.com/pydata/pandas-datareader/pull/403

**Comment by knabben** [comment]
With https I have a JSONDecodeError on google/quotes.py:30

result = json.loads(buffer[m.start() + len('// '):])

**Comment by davidastephens** [comment]
Fixed in #404

**Pull request closed without merging**
