### PR TITLE
remove string ',' in quote price

### PR DESCRIPTION
**Pull request by silau2005**
replace(',','')
this will facilitate the conversion from string to float, and avoid exception

### CODE REVIEW

**Comment by silau2005** [comment]
this string ',' removal is especially important for handling index price
e.g. INDEXHANGSENG:HSI
the original quote price is a string with ',' to show the thousand price point
which will cause error when converting to float

**Comment by femtotrader** [comment]
`read_csv` have a parameter `thousands`
see http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by femtotrader** [comment]
This PR should close #335

**Comment by femtotrader** [comment]
For PEP8 you should write

    .replace(',', '')

instead of

    .replace(',','')

**Comment by jreback** [comment]
thanks.

**Pull request merged**
