### PR TITLE
COMPAT: Add forward compat for is_list_like

### PR DESCRIPTION
**Pull request by bashtage**
Pandas 0.23 moves is_list_like
Add import to compat

- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by JordanPlatts** [comment]
Will this pr fix https://stackoverflow.com/questions/50394873/import-pandas-datareader-gives-importerror-cannot-import-name-is-list-like# ?

**Comment by addisonlynch** [comment]
@JordanPlatts yes.

**Comment by kfirbreger** [comment]
Its still not fixed. Replacing it as per https://stackoverflow.com/questions/50394873/import-pandas-datareader-gives-importerror-cannot-import-name-is-list-like does seem to work. So:

`from pandas.api.types import is_list_like`

Would you like a pull request with the change?

**Comment by addisonlynch** [comment]
@kfirbreger it was fixed with this PR. Download the dev version per the docs (``pip3 install git+https://github.com/pydata/pandas-datareader``) and it will work fine.

**Comment by pcacentral** [comment]
To download the recent dev version does not work as of today.  Not implemented in pandas-datareader 0.6.0+30.g3c17058

**Pull request merged**
