### PR TITLE
Added `data_source='yahoo-dividends'` option to DataReader.

### PR DESCRIPTION
**Pull request by jtkiley**
The existing dividend support pulls dividends as part of actions, but it's often desirable (for me anyway) to have just the dividends (and to pull a large number of symbols). The functionality is already there in `YahooDailyReader`, and this PR just creates an option that exposes it in `DataReader`.

### CODE REVIEW

**Comment by davidastephens** [comment]
Thanks.  Can you add a comment in the release note and reference in the docs?

**Comment by davidastephens** [comment]
Can you also add a test please?

**Comment by davidastephens** [comment]
Perfect, can you please squash and I will merge.

**Comment by jtkiley** [comment]
Squashed!

**Comment by davidastephens** [comment]
Perfect, thanks for the contribution!

**Pull request merged**
