### PR TITLE
CLN: Cleanup WorldBank reader

### LINKED ISSUE #120: wb.py needs a rewrite
Hello,

I think that all DataReaders are now objects except `wb.py` maybe this file need a rewrite.

see also https://github.com/pydata/pandas-datareader/issues/117

It should help to have cache support for World Bank https://github.com/pydata/pandas-datareader/issues/48

One possible API usage could be

    import requests_cache
    import datetime
    session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=datetime.timedelta(days=60))
    DataReaderObject("wb", session=session).search(string='gdp.*capi', field='name', case=False)
    DataReaderObject("wb", session=session).get_indicators()

Kind regards

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #120 to remove ``urlopen``. 

Related #119, changed some default arg using ``list`` to ``None`` (and set them in the method).

 CC @femtotrader

### CODE REVIEW

**Comment by femtotrader** [comment]
You might pass session parameter to each function which should download data in order to also provide cache mechanism to WorldBank data reader. (CC @davidastephens )

An other rewrite (maybe in a next release) will be to create a class.

**Comment by femtotrader** [comment]
Sorry. In fact, there is now a class `WorldBankReader` which is a great improvement.

but you might to also pass session to `download`, `get_countries`, `get_indicators`, `search` and send this session parameter to `WorldBankReader`

**Comment by femtotrader** [comment]
An other improvement might be about `errors` parameter.

We should use string but Enum (enum34 for Python 2) as it wil allow tab completion.

**Comment by femtotrader** [comment]
A last idea (about methods of WorldBankReader)...

`get_countries` and `get_indicators` might be properties named `countries` and `indicators` are there is no parameter (except `self`) for these 2 WorldBankReader methods.

**Comment by femtotrader** [comment]
I thought that it was the last idea... but sorry I also noticed that there is a `per_page` parameter in urls.

We might support chunks and use `page` parameter

try
http://api.worldbank.org/countries/?per_page=1000000&format=json&page=1

and

http://api.worldbank.org/countries/?per_page=10&format=json&page=1
http://api.worldbank.org/countries/?per_page=10&format=json&page=2

but this is probably out of the scope of this PR and an issue should be opened for this.

**Comment by sinhrks** [comment]
@femtotrader Thanks for the comments. I've updated the PR as below. I intend this PR to cover existing functionality, and others should be handled separately.

- **Add ``session`` to WB's ``get_xxx`` funcs:** Done. As other kw such as retry may be useful, passed all kwds to ``WorldBankReader`` class (same as other ``get_data_xxx`` funcs)

- **Change ``get_indicators`` and ``get_countries`` to property:** Don't do. I don't think the names are very understandable for users which is different from plain ``get_xxx`` functions. 

- **Change ``errors`` to enum:** Don't do in this PR. Because ``pandas`` doesn't use enum. Pls prepare a PR separately.

- **Add ``page`` param:** Don't do in this PR.

**Comment by femtotrader** [comment]
Thanks a lot for you work. You are right! Other improvements should be done in an other PR.

**Comment by femtotrader** [comment]
Sorry @sinhrks I think that ther is a mistake with

    return WorldBankReader().get_countries(**kwargs)

it might be

    return WorldBankReader(**kwargs).get_countries()

**Comment by sinhrks** [comment]
@femtotrader Thanks! Fixed and added tests.

**Pull request merged**
