### PR TITLE
New FRED URL

### PR DESCRIPTION
**Pull request by jhoodsmith**
Updated url to reflect the changes by fred.stlouisfed.org for downloading CSV.

### CODE REVIEW

**Comment by bashtage** [comment]
This looks right and the FRED tests pass

**Comment by bashtage** [comment]
Can you rebase on master?  It should pass and then this can be merged.

**Comment by rsvp** [comment]
It is not clear whether the new URL schema at FRED is stable. 
For example, the default values on their qualifiers (see #435) 
may change without notice to pandas_datareader users, 
which will unexpectedly transform datasets.

The old URL is still operational, so it may be a good idea 
to wait to pull until revisions to the FRED API are made "official."

**Comment by jhoodsmith** [comment]
For what it's worth, I agree with @rsvp. The new code is there if needed, but for the time being I suggest we follow the 'if it ain't broke, don't fix' strategy. Thank you to @bashtage for fixing the testing suit though.

**Comment by bashtage** [comment]
The right way is https://research.stlouisfed.org/docs/api/fred/ but this requires an API key.  The graph endpoint has been around for years and is used extensively through FRED to power the graphs.

**Comment by bashtage** [comment]
Accidental close.

**Comment by bashtage** [comment]
Also worth noting that this new endpoint is where data comes from when one interactively downloads data.

**Comment by bashtage** [comment]
I'm going to merge this.  I think it is the right endpoint since it is where data comes from when it is manually downloaded and there is no officially supported one.

**Pull request merged**
