### PR TITLE
Adding yahoo finance documentation

### LINKED ISSUE #817: Simple question about documentation
Why isn't the yahoo finance API listed in the Data Readers [list](https://pandas-datareader.readthedocs.io/en/latest/readers/index.html), but it is available as get_data_yahoo()? Will the get_data_yahoo() function be deprecated in future versions?

### PR DESCRIPTION
**Pull request by lukashalim**
- [ ] closes #817 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] passes `black --check pandas_datareader`
- [ ] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by lukashalim** [comment]
I think this version is better.
I renamed v0.9.1.txt because the file name had an "." in the wrong place, which was causing an error when I tried to build the documentation.

**Comment by bashtage** [comment]
Can you unstage the sqllite file.  This should not be added.

**Comment by bashtage** [comment]
After that it should be good.  The rename is fine with me.

**Comment by lukashalim** [comment]
I'm unfortunately stuck on unstaging the file.

**Comment by lukashalim** [comment]
Okay, I think I finally have it - I just went to my fork and deleted cache.sqlite

**Comment by bashtage** [comment]
LGTM.

**Pull request merged**
