### PR TITLE
Add back google

### LINKED ISSUE #551: Google Finance
As far as I understand, the Google Finance API is currently not supported. However, it seems that other projects such as
https://github.com/pdevty/googlefinance-client-python

are obtaining historical data from Google using the following URL:
https://finance.google.com/finance/getprices

Is there a reason why we can not do the same?

### PR DESCRIPTION
**Pull request by stoffprof**
- [x] closes #551
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by stoffprof** [comment]
Finally. Thanks @addisonlynch for much help with git

**Comment by addisonlynch** [comment]
Huzzah @stoffprof!

**Comment by rsvp** [comment]
It appears that XFAIL should be placed on
`pandas_datareader/tests/yahoo/test_yahoo.py`

and XFAIL removed from
`pandas_datareader/tests/google/test_google.py`
but actually only the last test there unexpectedly passed.

**Comment by addisonlynch** [comment]
@rsvp #556 should repair the failing Yahoo test. 

@stoffprof can you take a look at the Google tests? If reinstating we will need to remove the xfails and rewrite as necessary.

**Comment by stoffprof** [comment]
@addisonlynch Does this mean just writing new tests? Some of existing ones don't apply anymore -- expecting a panel, using ticker symbols like 'NYSE:F', which the API doesn't seem to accept, etc.

**Comment by addisonlynch** [comment]
@stoffprof yes! Probably best to just scrap most of the old tests and write new ones. Exhaustiveness is key. I'd be happy to write them if you need.

**Comment by bashtage** [comment]
What is the status of this?  If it can be made to work, it would be good to get it in and then do a release to avoid the is_list_like issue.

**Comment by addisonlynch** [comment]
@stoffprof have you had the chance to review this? If not, I'd be happy to write the test if you give me perms on the fork.

**Comment by stoffprof** [comment]
Haven't been able to find time. Thanks if you can do it. I added you as a collaborator on my fork. Let me know if there's anything else.

**Comment by addisonlynch** [comment]
I'm getting this from ``get_data_google``:

image

**Comment by stoffprof** [comment]
That URL doesn't seem to work any more. I guess we'll have to just stick with Yahoo.

**Comment by addisonlynch** [comment]
@stoffprof can you close?

**Pull request closed without merging**
