### PR TITLE
ENH: support OECD datasource

### PR DESCRIPTION
**Pull request by sinhrks**
Would like to move some func from my local repo.

This allows to retrieve data from [OECD](http://stats.oecd.org).

```
import pandas_datareader.data as web
import datetime
df = web.DataReader('UN_DEN', 'oecd', end=datetime.datetime(2012, 1, 1))
df[['Japan', 'United States']]
# Country         Japan  United States
# Time                                
# 2010-01-01  18.387333      11.383460
# 2011-01-01  18.995042      11.329488
# 2012-01-01  17.972384      11.078848
```

Currently, test fails in Python 2.6 because I use json's ``object_pairs_hook``. Can I include ``simplejson`` as optional dependency, or should choose alternative impl?

### CODE REVIEW

**Comment by davidastephens** [comment]
Maybe include simplejson if on python 2.6?

**Comment by davidastephens** [comment]
Looks good to me.  Thanks!  Can you add a note to:
https://github.com/pydata/pandas-datareader/blob/master/docs/source/whatsnew/v0.2.0.txt

and we can merge and include in 0.2.0 (expected release on Friday along with Pandas 0.17.0).

**Comment by sinhrks** [comment]
Thanks for review. Added the release note.

**Comment by davidastephens** [comment]
Thanks!

**Comment by femtotrader** [comment]
I noticed this "related" Python project

http://pandasdmx.readthedocs.org/
https://github.com/dr-leo/pandasdmx

**Pull request merged**
