### PR TITLE
COMPAT for pandas 0.20.0

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jreback** [comment]
so this will all pdr to be imported; we had removed ``PandasError``. However there are still lots of testing stuff that is using 'internal' pandas things. So this needs to change.

@gfyoung any interest in fixing?

**Comment by jreback** [comment]
cc @davidastephens

**Comment by gfyoung** [comment]
@jreback : I don't fully understand what you wrote.  Could you clarify?

**Comment by jreback** [comment]
@gfyoung the test suite here is a) nose, b) uses lots of things we removed from pandas.util.testing. So best case would be to simply convert this to use pytest and use the public things in pandas.testing.

**Comment by gfyoung** [comment]
@jreback : Ah, I see.  I can have a look.

**Comment by bashtage** [comment]
LGTM

**Comment by gfyoung** [comment]
@jreback : I think it can be done, but I'm going to wait until this PR gets merged

**Comment by jreback** [comment]
ok, I kind of wanted to have actual tests. But yes this *does* fix the issues.

**Comment by jreback** [comment]
@gfyoung go to it!

**Comment by gfyoung** [comment]
@jreback : Travis seems to disagree that all compat issues have been addressed.

**Comment by gfyoung** [comment]
Actually, I see it's probably because `api.types` does not exist in older version of `pandas`.  Also, any reason that none of the tests install `pandas` from `master` ?

**Comment by gfyoung** [comment]
I'm putting up PR to immediately patch `api.types` failure.

**Comment by jreback** [comment]
@gfyoung the import works (which was the initial issue). now none of the tests work because
a) no testing on travis of 0.20.1 (don't need master, this is enough)
b) tm.TestCase is relied upon.
c) api.types.

**Comment by jreback** [comment]
FYI this still uses nose. I think easiest would be to simply change to pytest. (or can just remove tm.TestCase and fix things too)

**Comment by gfyoung** [comment]
@jreback : No, I believe that the test works when the CORRECT version of `pandas` is installed.  However, I don't see why not just patch the `api.types` failure (condition on `pandas` version) for the moment.

**Comment by gfyoung** [comment]
> no testing on travis of 0.20.1 (don't need master, this is enough)

Why not just add `master` to allowed failures?  Couldn't hurt, could it?

> tm.TestCase is relied upon

Well, that will be taken care of when I do the `pytest` conversion.

**Comment by jreback** [comment]
> Why not just add master to allowed failures? Couldn't hurt, could it?

sure, but have to install from daily wheels (which can do), but easier just to install latest :>

can do it in steps.

**Comment by gfyoung** [comment]
> sure, but have to install from daily wheels (which can do), but easier just to install latest

Fair enough.  I would prefer to install from daily wheels in the end, though I'm not sure how that is done.

> can do it in steps.

Agreed.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/ci/requirements-3.6_NUMPY_DEV.build.sh
except install pandas (and just install numpy first, otherwise I think it will attempt to build it which is bad).

**Comment by mrocklin** [comment]
When is this likely to be released?  I'm running a tutorial on Wednesday that uses this library and want to pin versions.  Should I pin 0.20.1 or 0.19?

**Comment by jreback** [comment]
https://github.com/pydata/pandas-datareader/issues/328

**Pull request merged**
