### PR TITLE
FIX correct license, package name and authors/email

### LINKED ISSUE #3: Decide on the package name
Currently, @hayd changed the package name to `pandas_datareader`. Is everybody satisfied with that? (to be clear: it is about the name that is `import`ed)

Personally, I find it a bit long, and I think I also don't really like the underscore in the name. But of course, it is just personal taste! (I justed wanted to bring up the discussion to have this now, and not later, and deliberately decide on this to keep it as it is or to change it). 
What about just `datareader`, or `pddatareader` (but that is a bit difficult with the two 'd's)

### PR DESCRIPTION
**Pull request by hayd**
Fixes #3 the name to pandas-datareader.

Corrects the license, url and contact info etc. for setup.py.

### CODE REVIEW

**Comment by hayd** [comment]
cc @jorisvandenbossche  @jreback does this look right/better?

**Comment by jorisvandenbossche** [comment]
@hayd You now included the pandas licence. I have to say, I don't know much about licenses, but shouldn't there also be a license that is mentioning pandas-datareader?

**Comment by dstephens99** [comment]
This looks fine to me (but I don't know anything about licences).  Is this good to go? @jorisvandenbossche @hayd @jreback

**Comment by hayd** [comment]
It could probably be modified in future to something like pandas-data-reader follows the pandas license, for now this is an obvious improvement.

**Pull request merged**
