### PR TITLE
Extended DataReader to fetch Dividends and Stock Splits from Yahoo!

### PR DESCRIPTION
**Pull request by brotchie**
- Added yahoo-actions data_source to DataReader;
 - Added get_data_yahoo_actions that returns a DataFrame containing
   DIVIDEND and SPLIT corporate actions fetched from Yahoo! Finance;
 - Added unit tests;
 - Added documentation example.

### CODE REVIEW

**Comment by dstephens99** [comment]
Thanks.  Could you add that to the docs? I assume that would be a common question.

Only other thing I could think of would be to have a convenient way to get only the splits or only the dividends (understanding that anyone could filter the resulting dataframe).  Could be next version..

**Comment by davidastephens** [comment]
@brotchie  Can you add the note to the docs about the date being the ex-date?  Then I'm good to merge.

Thanks!

**Comment by brotchie** [comment]
@davidastephens I've updated the appropriate docstrings and Sphinx documentation with details of ex-dates.

Cheers!

**Comment by davidastephens** [comment]
Great.  Thanks!  Can you squash and I'll merge when green?

**Pull request merged**
