### PR TITLE
DOC small formatting change in readme

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@dstephens99 Currently the readme is not nicely formatted on PyPI. And it is possible that it is just because of this formatting 'error'. 

Can you try this?

### CODE REVIEW

**Comment by dstephens99** [comment]
Sure.  I'm not that familiar with Pypi - but it seems like I can't change a release, so we'd have to do a v0.1.1 release in order to update this.  Unless there's a way to change it that I don't know about?

**Comment by jorisvandenbossche** [comment]
I think that you can just run `python setup.py register` again to update the metadata (but not sure, never done it myself)

**Comment by hayd** [comment]
You can just edit the manually on pypi (when logged in), no reuploading necessary. It *may* be because pypi doesn't support svg images, changing the svg to png in the badges may fix it.

**Comment by dstephens99** [comment]
Thanks - I edited the RST.  Works now (SVG is fine).

**Comment by hayd** [comment]
>  (SVG is fine).

pypi have fixed a bug, awesome!

**Comment by bashtage** [comment]
There appears to be a non-printing character in example

https://pypi.python.org/pypi/pandas-datareader/0.1.0

**Comment by dstephens99** [comment]
@bashtage Thanks.  Fixed in #32

**Pull request merged**
