### PR TITLE
Fix Yahoo! price data

### PR DESCRIPTION
**Pull request by stoffprof**
Adds back support for downloading price data (not actions yet) from Yahoo! (New to github, not sure I'm doing everything right.)

- [x] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by bashtage** [comment]
Need some flake8 fixes.

**Comment by stoffprof** [comment]
Can I get some guidance on this? I'm new here. Not sure what is needed.

**Comment by addisonlynch** [comment]
@stoffprof the code needs to pass a flake8 check...it's a formatting checker for [PEP-8](https://www.python.org/dev/peps/pep-0008/) and a few other things. I'll take a look and clean up what I can this evening.

**Comment by bashtage** [comment]
If you 

```
conda install flake8
```

or 

```
pip install flake8
```

then you can run `flake8 pandas_datareader` and get a report of lines of code that don't follow the PDR style.

**Comment by addisonlynch** [comment]
Uploaded a gist of the corrected formatting [here](https://gist.github.com/addisonlynch/c1570adbe823dd6114f28fcfd1d3e578) for reference.

**Comment by stoffprof** [comment]
I made the required flake8 changes to `daily.py`. Do I need to squash these two commits somehow?  Sorry for the newbie questions.

**Comment by stoffprof** [comment]
Another thing — accessing the data source this way gives all dividends and splits in the same JSON result as the prices. Right now I'm just throwing these out. Does it still make sense to have a separate function for actions? Since it's the same web query for both prices and actions maybe we should just return both results as a list of DataFrames. Very easy to do, I just wasn't sure if this would be considered an API-breaking change.

**Comment by bashtage** [comment]
Would be great to have readers for that too.

**Comment by bashtage** [comment]
Merged since failure was in Google.

**Comment by bashtage** [comment]
Thanks.

**Comment by Beetee32** [comment]
import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import fix_yahoo_finance


# Commodity Channel Index 
def CCI(data, ndays): 
 TP = (data['High'] + data['Low'] + data['Close']) / 3 
 CCI = pd.Series((TP - pd.rolling_mean(TP, ndays)) / (0.015*pd.rolling_std(TP, ndays)),
 name = 'CCI') 
 data = data.join(CCI) 
 return data

# Retrieve the Nifty data from Yahoo finance:
data = web.get_data_yahoo("^NSEI", start="2017-01-01", end="2018-01-01") 
data = pd.DataFrame(data)

# Compute the Commodity Channel Index(CCI) for NIFTY based on the 20-day Moving average
n = 20
NI = CCI(data, n)
CCI = NI['CCI']

# Plotting the Price Series chart and the Commodity Channel index below
fig = plt.figure(figsize=(7,5))
ax = fig.add_subplot(2, 1, 1)
ax.set_xticklabels([])
plt.plot(data['Close'],lw=1)
plt.title('NSE Price Chart')
plt.ylabel('Close Price')
plt.grid(True)
bx = fig.add_subplot(2, 1, 2)
plt.plot(CCI,'k',lw=0.75,linestyle='-',label='CCI')
plt.legend(loc=2,prop={'size':9.5})
plt.ylabel('CCI values')
plt.grid(True)
plt.setp(plt.gca().get_xticklabels(), rotation=30)
plt.show()


Can anyone please guide me to solve the following error ? 

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\cci.py", line 17, in <module>
    data = web.get_data_yahoo("^NSEI", start="2017-01-01", end="2018-01-01")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\data.py", line 63, in get_data_yahoo
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Actions'))
pandas_datareader.exceptions.ImmediateDeprecationError:
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

**Pull request merged**
