### PR TITLE
MAINT: Use isort to add consistency

### PR DESCRIPTION
**Pull request by bashtage**
Use isort to improve import consistency

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by addisonlynch** [comment]
Can probably update PR template for new formatting requirements (passes ____)

**Comment by bashtage** [comment]
Will alter in a later PR.  Thinking about blackening the code. What do you think?

**Comment by addisonlynch** [comment]
I think that's a good idea...I'm not too familiar with black (other than a little time spent on pandas) but if it takes care of most of the heavy lifting for contributors, all the better. For CI we would use ``black --check``?

**Comment by bashtage** [comment]
Yes, that is right. Black simplifies formatting with contributors.

**Pull request merged**
