### PR TITLE
COMPAT: Repair PY2 issues

### LINKED ISSUE #665: Not working with new pandas versions
When i'm trying install `pandas-datareader` both with `pandas >= 0.25.0`
i getting error like `AttributeError: module 'pandas.compat' has no attribute 'binary_type'` when trying loading data from MOEX for example.
I'm using `pandas==0.24.2` and all working fine. Please, fix this issue!

### PR DESCRIPTION
**Pull request by addisonlynch**
Merging 0.7.4 py2 compat changes into master in prep for 0.8.0

- [x] closes #665
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by bashtage** [comment]
The important question is whether pdr should be Python 3 only for 0.8 on, in which case all of the PY2/3 compat code can be removed

**Comment by bashtage** [comment]
Either 0.8 is the last PY2 compat release of 0.7 is the last PY2 release.  If it is the latter, then we can remove all PY2/3 code now.

**Comment by bashtage** [comment]
Need to add 3.7 for testing and get tests/xfail before release.

**Comment by gliptak** [comment]
With build green, could 0.8.0pre be tagged?

**Comment by bashtage** [comment]
I think docs need to be updated before the tag, but close.

**Comment by bashtage** [comment]
FWIW current master is now correctly tagged 0.8.0dev0

**Pull request merged**
