### PR TITLE
CLN: Cleanup option reader

### PR DESCRIPTION
**Pull request by sinhrks**
Cleanup and added some tests.

### CODE REVIEW

**Comment by gliptak** [comment]
@sinhrks I would like to propose simplifying the Options approach. The steps to obtain options data would be:

1. Get list of expiry dates (varies with weekly vs monthly only)
2. Get all options data for a particular expiry
3. Filter for call/put, strikes near current price, aggregate for all expiries for current month are to happen in calling code

PS Some of the current approach (in particular call/put separation) seem to have been driven by the Yahoo! web representation ...

**Comment by sinhrks** [comment]
Thanks. Because I don't familiar with Yahoo/google quotes API, could you do it separately?

**Comment by gliptak** [comment]
@sinhrks I'm not sure what you refer above as "separately" (in a separate pull request?) What I'm describing above, is a proposed cleanup of the API (really leaving two methods, get ```expiry_dates``` and ```get_options_data``` for a particular expiry date) working the same for both Yahoo and Google.

**Comment by sinhrks** [comment]
Yes, separate PR. I'm not quite understood the suggested change.

**Comment by gliptak** [comment]
Sure. I will wait until this one is committed.

**Comment by sinhrks** [comment]
If there is no comments, will merge within few days.

**Comment by femtotrader** [comment]
+1 let's merge it! thanks @gliptak

**Pull request merged**
