### PR TITLE
TST: Update tests to pandas 0.17.0rc2

### PR DESCRIPTION
**Pull request by davidastephens**
#70

### CODE REVIEW

**Comment by jreback** [comment]
btw u can also add py35

**Comment by davidastephens** [comment]
Looks like there is no conda package for py35 and beautiful soup.  Any way around this?  

Error: Unsatisfiable package specifications.

Hint: the following packages conflict with each other:
  - python 3.5*
  - beautiful-soup

**Comment by jreback** [comment]
need to pip installl beautiful-soup (for now)

**Comment by davidastephens** [comment]
Thanks.  That's what I figured. 

Need to fix for change in convert_objects as well.

**Pull request merged**
