### PR TITLE
CLN: Cleanup subclass

### LINKED ISSUE #106: Cleanup subclass structures
There are few options commonly used in some readers, such as proxy and cache(#48). How about:

- Change read functions to classes which has common base class.
- Use ``requests`` to get raw files rather than ``urlopen``.

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #106. Clean-up most of classes to use common logic.

### CODE REVIEW

**Comment by femtotrader** [comment]
Your `BaseReader` should probably have a `_get_session` method

```
def _get_session(self, session):
    """Returns a requests.Session if session is None
    or session if it's not None (cached session
    with requests-cache for example)
    :param session:
    :return:
    """
    if session is None:
        session = requests.Session()
    return session
```

and `__init__` should accept a `session` parameter (default to `None`)

so we will do

    self.session = _get_session(session)

this will allow to pass a session (with proxy or cache)

**Comment by sinhrks** [comment]
OK, updated to add a ``session``, I've chosen a word "init" as it is not for getting.

BTW, found a problem that ``requests`` doesn't allow to specify pausing between retry. Thus, current ``pause`` kw can't work now... I'll implement retry-pause logic by myself.

**Comment by sinhrks** [comment]
Implemented the logic to handle retry and pause. Now ready for review.

**Comment by femtotrader** [comment]
Sorry but I don't see commit

https://github.com/sinhrks/pandas-datareader/tree/cln_subclass

**Comment by sinhrks** [comment]
It's squashed to the single commit, following pandas manners.

**Comment by femtotrader** [comment]
Ok yes sorry... I was mistaken by commit date.

**Comment by bashtage** [comment]
Is anything in `base` for public use?  If not private seems more correct.

**Comment by sinhrks** [comment]
@bashtage No, changed it to private. Rebased and squashed.

**Comment by davidastephens** [comment]
Thanks @sinhrks  This looks great.

**Pull request merged**
