### PR TITLE
CLN: Split into subpackages

### LINKED ISSUE #58: One file per datareader
Hello,

`data.py` is a very (too) big file.

I think we should have one file per datareader.

Moreover this will help https://github.com/pydata/pandas-datareader/issues/48

I've done on my fork a branch where each datareader is a file.

    $ nosetests -s -v

shows

    Ran 58 tests in 83.806s
    FAILED (SKIP=7, errors=10, failures=3)

that's exactly same result with this `master` branch.

I will send a PR.

Kind regards

### PR DESCRIPTION
**Pull request by davidastephens**
@femtotrader @bashtage 

Everyone fine with this version?

Fixes #58, replaces #68.

### CODE REVIEW

**Comment by hayd** [comment]
Personally I would prefer util or utils to common. But this is a big improvement overall. :+1:

**Comment by davidastephens** [comment]
@hayd  Agreed, this is a big improvement - thanks @femtotrader.

I'll change to util..

Other than compatibility, data.py is redundant now.  May be worth changing it to api.py and importing everything to the top level.

**Comment by hayd** [comment]
The data.py is for backwards compat. The old API should remain available for a good while. Though there are other ways to get the same behaviour. IMO without a deprecation message.

**Comment by bashtage** [comment]
I agree that importing `data` should remain supported for the next few releases.

**Comment by femtotrader** [comment]
I noticed that `google.daily` provide only daily data but `yahoo.daily` can provide other interval

maybe `yahoo.daily` should be named differently.

But thanks for merging.

**Pull request merged**
