### PR TITLE
FIX Yahoo Actions with several symbols

### PR DESCRIPTION
**Pull request by femtotrader**
Might fix https://github.com/pydata/pandas-datareader/issues/137

CC @davidastephens @sinhrks

### CODE REVIEW

**Comment by davidastephens** [comment]
Can you add a test to confirm the fix?

**Comment by femtotrader** [comment]
Done

**Comment by sinhrks** [comment]
There are readers which can read multiple symbols. Making them to use the same API looks good (I don't persis current master's impl) :)

**Comment by davidastephens** [comment]
Thanks - can you rebase and squash?

**Comment by femtotrader** [comment]
I'm using `_DailyBaseReader` now but I don't feel confortable with rebase

see

```
git rebase HEAD~5
```

I changed to 

```
pick 618a666 FIX Yahoo Actions with several symbols
s db43165 Minor fix
s 359cbbc SymbolWarning was missing
s bb339a6 Add unit test for Yahoo Actions with several symbols
s 59157f0 Using _DailyBaseReader
````

Commit message was set to

```
FIX Yahoo Actions with several symbols
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Mon Dec 7 22:32:41 2015 +0100
#
# rebase in progress; onto eca4f8f
# You are currently editing a commit while rebasing branch 'fix_yahoo_actions_several' on 'eca4f8f'.
#
# Changes to be committed:
#       modified:   pandas_datareader/tests/test_data.py
#       modified:   pandas_datareader/yahoo/actions.py
```

It displays

```
[detached HEAD 8370604] FIX Yahoo Actions with several symbols
 Date: Mon Dec 7 22:32:41 2015 +0100
 2 files changed, 16 insertions(+), 7 deletions(-)
Successfully rebased and updated refs/heads/fix_yahoo_actions_several.
```

But 

```
 git push
To https://femtotrader@github.com/femtotrader/pandas-datareader
 ! [rejected]        fix_yahoo_actions_several -> fix_yahoo_actions_several (non-fast-forward)
error: failed to push some refs to 'https://femtotrader@github.com/femtotrader/pandas-datareader'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

so I did a `git pull` and a `git push`

but it didn't work as I was expecting.

I would be please to know how to squash.

**Comment by davidastephens** [comment]
try this:
```
git fetch upstream

git rebase upstream master -i

[change all but one of the commits to s]

git push -f (you have to force it because you are changing the history.
```

**Comment by femtotrader** [comment]
I really need to learn to squash commits ;-)

```
$ git fetch upstream
$ git rebase upstream/master -i
error: could not apply 618a666... FIX Yahoo Actions with several symbols

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply 618a6660edcac323dde0898f1bae8319bc5857ef... FIX Yahoo Actions with several symbols
```

Sorry

**Comment by davidastephens** [comment]
You are almost there, you just have a merge conflict you have to deal with.  You can just check the file that has the conflict (it will have a HEAD>>>>> section where the conflict is) or use an IDE or merging tool (like meld) to resolve the conflict.  

Then do:

```
git add [filename that you fixed]
git rebase --continue
git push -f
```

**Pull request closed without merging**
