### PR TITLE
COMPAT: Migrate IEX Daily Reader to IEX Cloud

### PR DESCRIPTION
**Pull request by addisonlynch**
As discussed in #623, IEX is migrating to a new platform, [IEX Cloud](https://iexcloud.io) on June 1, 2019. At this time, support for the legacy API (existing source for PDR's IEX readers) will end.

This PR migrates ``IEXDailyReader`` to IEX Cloud. Additional work to follow will migrate the remainder of the readers.

IEX provides a sandbox environment, which must be enabled by setting ``IEX_SANDBOX`` to ``enable`` to run tests. A test API key must be used (from IEX Cloud console). 

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by addisonlynch** [comment]
@bashtage will probably want to cut a release for this. Seems to be one of the higher-usage readers and will break when the legacy platform is continued on 6/1. I'll see if I can migrate the rest of the readers before then.

**Comment by bashtage** [comment]
Any idea what is actually broken?  And is it fixable or does it need immediate deprecation

**Comment by addisonlynch** [comment]
IEX is migrating off of their legacy API (a free, no auth service) to IEX Cloud which requires auth. URL changes but functionality is the same. This reader will break on 6/1...don't see a need to deprecate and create a new one and add auth. Adding auth to this reader should be fine with a few other smaller modifications. I realized I need to clean up one small caveat with the test suite here then will be good to go.

**Comment by addisonlynch** [comment]
@bashtage can you review & merge? IEX readers are now dead from provider as is

**Comment by jzstoller** [comment]
Any idea when this might be fixed? thanks!

**Pull request merged**
