### PR TITLE
Adding back more Yahoo! data

### LINKED ISSUE #487: ImmediateDeprecationError:  Yahoo Actions has been immediately deprecated due to large breaks in the API without the introduction of a stable replacement.
Yahoo Finance data looks not working well not 2018/2/14:

ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

### PR DESCRIPTION
**Pull request by stoffprof**
- [x] closes #487
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/source/whatsnew/vLATEST.txt

`YahooDailyReader` now returns a `dict` of `DataFrames` for `prices`, `dividends`, and `splits`. Only one web query is necessary for each ticker to get all data.

Currency data may now be accessed with the `YahooFXReader`.

Chunking and return index not properly implemented yet.

### CODE REVIEW

**Comment by okomarov** [comment]
@bashtage Any progress on this PR?

**Comment by JmsBlah** [comment]
How to install this new version?

**Comment by bashtage** [comment]
@stoffprof Is this working?

**Comment by stoffprof** [comment]
I believe so.

**Pull request closed without merging**
