### PR TITLE
Fix Split calculation in YahooActionReader

### PR DESCRIPTION
**Pull request by tibkiss**
See https://github.com/pydata/pandas-datareader/issues/396 for details.

### CODE REVIEW

**Comment by bashtage** [comment]
Should have a comment with the GH issue number that identified it (# GH #396)

**Comment by bashtage** [comment]
Any reason not to just import 

from __future__ import division

?

**Comment by tibkiss** [comment]
@bashtage : Thanks for the prompt review, update the PR accordingly.

**Comment by tibkiss** [comment]
The errors seems unrelated to me. Could someone please confirm too?

**Comment by tibkiss** [comment]
@gliptak : PTAL

**Comment by tibkiss** [comment]
I've encountered a ZeroDivisionError for a given security in the same code path. Shall I include handling such errors in this PR or rather open a new one?

**Comment by bashtage** [comment]
Fixing in this PR would be good.

**Comment by tibkiss** [comment]
will open a new pr.

**Pull request closed without merging**
