### PR TITLE
Fix various failures in tests

### PR DESCRIPTION
**Pull request by davidastephens**

### CODE REVIEW

**Comment by davidastephens** [comment]
resolves: #403 
resolves: #402 
fixes: #394 
fixes: #395

**Comment by rsvp** [comment]
@davidastephens For the Google Finance test fix, the use of *pytest.skip* 
seems too definitive in the sense that Google may reconsider its API changes 
during the reconstruction period. So how about using *pytest.xfail* or even more 
explicitly `@pytest.mark.xfail()` with condition and reason attached?
See https://docs.pytest.org/en/latest/skipping.html

That way we can later run: `pytest --runxfail`
to see if Google has reverted without much hassle, 
and just remove the decorators.
(Historically, Google has reversed its pronouncements on quote 
retrieval via Sheets, so there's hope if there's enough public outcry :-).

**Comment by rsvp** [comment]
hi @davidastephens -- could you kindly summarize what was fixed?

Many disparate issues were closed, so it might be useful to
***review the root problems which were solved***.

In what pandas_datareader version will the fixes be distributed? Thanks!

**Comment by davidastephens** [comment]
Hi @rsvp: Each commit has detail as to what was fixed.  I aggregated into one pull request so I could get the travis tests to pass.

These fixes will be distributed in 0.6.0, but unfortunately, a significant portion of this package no longer works due to API removals.  I've noted which apis no longer work in the docs and skipped the tests, but unsure if we should do anything in the code.  Would adding DeprecationWarnings be helpful?

**Comment by rsvp** [comment]
@davidastephens: hi, I think DeprecationWarnings would be most helpful 
since users would understand their own working code is not at fault, 
but rather API changes from the data vendors. The warnings should 
point to a summary page where the problems and limitations have 
been detailed, and possible remedies discussed. 

My best summary is here:  https://github.com/rsvp/fecon235/issues/7 
but when pandas_datareader 0.6.0 ships :shipit: I can write up a 
clean wiki page. I suggest  **pddr404api** as the hashtag keyword 
since that currently has no document matches via a Google search.

**Pull request merged**
