### PR TITLE
Update Yahoo _get_crumb

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

This is intended to correct the intermittent crumb error.

https://travis-ci.org/gliptak/pandas-datareader/builds/250129519

https://github.com/pydata/pandas-datareader/issues/356

### CODE REVIEW

**Comment by jreback** [comment]
if this passes, can you try removing the xfails and push again as I suggest https://github.com/pydata/pandas-datareader/issues/356#issuecomment-312951370

**Comment by gliptak** [comment]
@jreback I don't see this correcting the SPLIT and 251/252 failures (from https://github.com/pydata/pandas-datareader/issues/356#issuecomment-312946328)

**Comment by jreback** [comment]
@gliptak ok this looks fine. what is it intended to solve?

**Comment by gliptak** [comment]
I'm seeing exceptions like below, but I just noticed that the above change doesn't correct them (although it simplifies the code)

```
/pandas/local/lib/python2.7/site-packages/pandas_datareader/base.pyc in _get_response(self, url, params, headers)
    140         if params is not None and len(params) > 0:
    141             url = url + "?" + urlencode(params)
--> 142         raise RemoteDataError('Unable to read URL: {0}'.format(url))
    143 
    144     def _get_crumb(self, *args):

RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/AAPL?crumb=HrMgz4DEURf&interval=1d&period2=1499208155&events=div&period1=1262322000
```

The URL content is:
```
{
    "finance": {
        "error": {
            "code": "Unauthorized",
            "description": "Invalid cookie"
        }
    }
}
```

**Pull request closed without merging**
