### PR TITLE
avoid monkey patching requests.Session Fixes #301

### LINKED ISSUE #301: avoid monkeypatching requests session and use requests_ftp.frp.FTPSession directly
or avoid the porcelain methods, and only use:

```python
session.request('RETR', url, **kwargs)
```

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
actually from a quick glance it looks like you're not even using any of the special FTP methods!

I've changed this so it just mounts the FTPAdapter.

**Comment by jreback** [comment]
why is this necessary?

**Comment by jreback** [comment]
why is this necessary?

**Comment by graingert** [comment]
@jreback to avoid monkey patching requests.Session and fix #301

**Comment by graingert** [comment]
@jreback to avoid monkey patching requests.Session and fix #301

**Comment by graingert** [comment]
@jreback seriously though, monkey patching requests with a 'really silly library' is not generally a good idea. https://github.com/Lukasa/requests-ftp/pull/31/files. The real reason for issue #301 was because this was messing up my tests with pyvcr, and so I had to monkey patch requests.Session back to what it's supposed to be after importing datareader.

**Comment by graingert** [comment]
@jreback I've now updated the documentation to make it more clear when to use monkeypatch_session:

https://github.com/Lukasa/requests-ftp#monkey-patching

**Comment by jreback** [comment]
can you add a whatsnew entry for 0.5.0. otherwise lgtm. (rebase on master as well). ping on green.

**Comment by graingert** [comment]
@jreback done

**Comment by jreback** [comment]
thanks.

**Comment by graingert** [comment]
@jreback it's green, bet you wish github had GitLab's merge when green button

**Comment by jreback** [comment]
hahha @graingert yeah we use gitlab elsewhere, though to be honest I don't usually use the button :>

**Comment by jreback** [comment]
thanks for the fix!

**Comment by graingert** [comment]
🔥🐒 💥

**Pull request merged**
