### PR TITLE
Added Morningstar Data

### PR DESCRIPTION
**Pull request by dtemkin**
I added access to Morningstar Daily OHLCV Quotes and Financial Statements (with Key Ratios). Still working on function to adjust close prices.

### CODE REVIEW

**Comment by rsvp** [comment]
Which specific Morningstar URLs does MorningstarDailyReader utilize?

**Comment by davidastephens** [comment]
Thanks - can you add some tests and docs?

**Comment by dtemkin** [comment]
@rsvp I used:  http://globalquote.morningstar.com/globalcomponent/RealtimeHistoricalStockData.ashx
I also read your reference - from what I could see the major issue in travisci wasnt my code, it was the enigma component that was throwing up errors. Tried a few basic fixes we will see if the next commit passes. 
@davidastephens I am doing it as we speak. Just trying to be as complete and consistent as possible. Sorry for the delay.

**Comment by bashtage** [comment]
Can you rebase on master so we can see if things pass.

**Comment by paintdog** [comment]
Could you say something about which countries and which indices with their stocks - to what depth (the most important index in a country and / or smaller indices) - are covered?

**Comment by bashtage** [comment]
@dtemkin any chance you could get this in shape in the next few days?  Trying to get a new release out.

**Comment by dtemkin** [comment]
@bashtage I will do it over the weekend. Sorry for being such a |300|3 this just kept getting backburnered but I will rebase and add the unit tests.

**Comment by bashtage** [comment]
That would be great -- it will definitely get into 0.6.0 if you can get it
done.

**Comment by bashtage** [comment]
This needs a rebase onto master.  If you find this hard, ping me and I'll open a PR on your branch with the rebase.

**Comment by dtemkin** [comment]
@bashtage So my latest PR failed due to a failed attribute reference in setup.py. Would you like me to try and fix it? I have never used ast personally and I don't see any "values" or "value" attribute reference on the parse function but I could still give it a shot.

**Comment by bashtage** [comment]
This is going to need some git surgery.  I'll make a PR to your repo.

**Comment by dtemkin** [comment]
OK sounds good. Sorry if I didn't rebase correctly. I will keep an eye out for the PR. Thanks for everything.

**Comment by bashtage** [comment]
This should get  you a clean branch

```
git remote add bashtage https://github.com/bashtage/pandas-datareader
git fetch --all
git checkout -b mstar bashtage/dtemkin-mstar
git push -u origin mstar
```

Once you've run this, you can open a new PR from the mstar branch, and then make any final changes to this.

**Comment by bashtage** [comment]
Going to close this in favor of #467

**Pull request closed without merging**
