### PR TITLE
Fix Eurostat and OECD tests that fail.

### PR DESCRIPTION
**Pull request by jtkiley**
The tests error or fail, but the data pulls still work. I'll put together what I can find about data changes and file an issue tomorrow.

### CODE REVIEW

**Comment by jtkiley** [comment]
This is good to go.

**Comment by jtkiley** [comment]
Having looked into it for a bit, I can now see straightforward fixes for these to address the source data changes causing each to fail.

**Comment by jtkiley** [comment]
@davidastephens: This is ready to go. If you agree, I'll squash.

I went ahead and fixed the linting issues in these files, because I was already editing the majority of the lines with issues.

**Comment by davidastephens** [comment]
Looks good.  Please squash and I can merge.

**Comment by jtkiley** [comment]
Done!

**Comment by femtotrader** [comment]
Closes https://github.com/pydata/pandas-datareader/issues/164

**Pull request merged**
