### PR TITLE
BUG: Fix yahoo options

### PR DESCRIPTION
**Pull request by beluga9**
This updates yahoo_options to use the json endpoint that's now in use by the Yahoo Finance site (Issue #212)

It adds the following columns to the existing list of columns:
- `Last_Trade_Date`: the last trade datetime
- `JSON`: a JSON object containing the raw json, which can be useful if additional data is needed that is not in the DataFrame's columns

### CODE REVIEW

**Comment by femtotrader** [comment]
Thanks @beluga9 
Don't worry CI is failing because of EDGAR tests https://github.com/pydata/pandas-datareader/issues/226
Pinging @jtkiley

**Comment by duncangh** [comment]
Hi, I apologize if this is not the correct channel for this note, I am new to Github. I've retrofitted some of the original Options code to work on nasdaq's options pages. Also working to do the same for Financial Statement data from zacks.com (BS, IS and SCF). I would love to contribute to this project, but am new to source control. Feel free to contact me at duncangh@email.wofford.edu with feedback or suggestions. 

Thank you all for developing such a great project. I am extremely impressed by the scope of data accessibility provided by datareader. 

Best, 
Graham H. Duncan
[Nasdaq Options.txt](https://github.com/pydata/pandas-datareader/files/535063/Nasdaq.Options.txt)

**Comment by femtotrader** [comment]
@beluga9 there are some (minor) flake8 errors

see
https://travis-ci.org/pydata/pandas-datareader/jobs/162668229

```python
The command "nosetests -v --with-coverage --cover-package=pandas_datareader" exited with 0.
1.14s$ flake8 --ignore E501 pandas_datareader
pandas_datareader/yahoo/options.py:138:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:161:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:586:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:599:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:612:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:695:5: E303 too many blank lines (2)
pandas_datareader/yahoo/options.py:745:5: E303 too many blank lines (2)
```

Could you fix them?

That will be very nice.

**Comment by jamestbrown** [comment]
👍 This is amazing! Thank you!

**Comment by femtotrader** [comment]
If everyone is ok I will merge this great PR in the next coming days.
Thanks @beluga9

**Comment by jamestbrown** [comment]
Thanks!

**Comment by MaxGally** [comment]
How can I upgrade to the latest version of pandas_datareader? I have run "pip install --upgrade pandas_datareader". If I run "import pandas_datareader as pd", "pd.__version__". I get '0.2.1'.
It looks that the Yahoo fix is in version 0.2.2.
My goal is to be able to query Yahoo in order to retrieve stop options values.
Thank you.

**Comment by femtotrader** [comment]
Latest version of pandas_datareader is not published on Pypi.
So you might install latest development version

    $ pip install git+https://github.com/pydata/pandas-datareader.git

or

    $ git clone https://github.com/pydata/pandas-datareader.git
    $ python setup.py install

**Comment by MaxGally** [comment]
Thank you

**Pull request merged**
