### PR TITLE
Read requirements.txt during setup

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@bashtage please review

**Comment by addisonlynch** [comment]
@gliptak is it worth it to add a ``tests_require`` for requirements-dev.txt? Perhaps both could be used to clean up CI as well:

https://github.com/pydata/pandas-datareader/blob/3e14574d45f88aecb44e599d37e3ebc3ff701168/.travis.yml#L62-82

**Comment by gliptak** [comment]
@addisonlynch added ```tests_require``` thanks for the pointer

https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=tests_require#new-and-changed-setup-keywords

**Comment by gliptak** [comment]
@addisonlynch as for ```.travis.yml``` update, it might be better to attempt it when the builds are green ...

https://github.com/pydata/pandas-datareader/blob/master/.travis.yml#L60

**Comment by bashtage** [comment]
Thanks.

**Comment by gliptak** [comment]
@bashtage so you are not interested in the incremental improvement?

**Pull request closed without merging**
