### PR TITLE
Correct EcondbReader's API URL format

### PR DESCRIPTION
**Pull request by econdb**
Sets correct default query parameter before API requests.

Detailed documentation and usage examples to follow in 1 week.

### CODE REVIEW

**Comment by gliptak** [comment]
This still shows an Econdb error
https://travis-ci.org/pydata/pandas-datareader/jobs/582907139

```
_________________________ TestEcondb.test_get_tourism __________________________
self = <pandas_datareader.tests.test_econdb.TestEcondb object at 0x7fa06f666a10>
    def test_get_tourism(self):
        # OECD
        # TOURISM_INBOUND
    
        df = web.DataReader(
            'dataset=OE_TOURISM_INBOUND&COUNTRY=JPN,USA&'
            'VARIABLE=INB_ARRIVALS_TOTAL', 'econdb',
            start=pd.Timestamp('2008-01-01'), end=pd.Timestamp('2012-01-01'))
        df = df.astype(np.float)
        jp = np.array([8351000, 6790000, 8611000, 6219000,
                       8368000], dtype=float)
        us = np.array([175702309, 160507417, 164079732, 167600277,
                       171320408], dtype=float)
        index = pd.date_range('2008-01-01', '2012-01-01', freq='AS',
                              name='TIME_PERIOD')
    
        # sometimes the country and variable columns are swapped
>       lvl1 = df.columns.levels[0][0]
E       AttributeError: 'Index' object has no attribute 'levels'
pandas_datareader/tests/test_econdb.py:51: AttributeError
```

**Comment by econdb** [comment]
Should work now @gliptak , that dataset was briefly unavailable in the database.

**Comment by gliptak** [comment]
@econdb could you repush to trigger another build?

**Comment by gliptak** [comment]
@bashtage build is green for Econdb tests

https://travis-ci.org/pydata/pandas-datareader/builds/585071198

**Comment by bashtage** [comment]
Thanks.

**Pull request merged**
