### PR TITLE
Small fix on the comments and retry pause

### PR DESCRIPTION
**Pull request by keviny**
* Fix the comment
* Adjust the retry pause time, sometime 0.001s pause make the retry useless.

### CODE REVIEW

**Comment by davidastephens** [comment]
Thanks - looks good.  Can you squash this?

**Comment by keviny** [comment]
You mean fix the coverage?
Sorry, this is my first try to submit some code on github.

**Comment by davidastephens** [comment]
Please see here:
http://pandas.pydata.org/pandas-docs/stable/contributing.html#id26

**Comment by davidastephens** [comment]
Please see here:
http://pandas.pydata.org/pandas-docs/stable/contributing.html#combining-commits

**Comment by davidastephens** [comment]
Closed by #166

**Pull request closed without merging**
